// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpLg6f-iAMeuHE2R2HcavpOmx3uQUoZDo',
    appId: '1:374957165391:web:01b911c6cca3f73b3fd33a',
    messagingSenderId: '374957165391',
    projectId: 'universityfirebase-155dd',
    authDomain: 'universityfirebase-155dd.firebaseapp.com',
    storageBucket: 'universityfirebase-155dd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-sQhQ0KwZnVNrVAyf0fI-ol2yQ9mjoho',
    appId: '1:374957165391:android:99593c60e9779c443fd33a',
    messagingSenderId: '374957165391',
    projectId: 'universityfirebase-155dd',
    storageBucket: 'universityfirebase-155dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrTwLPthJrV0i4abC7Z4xxSzfXJ6-sZxk',
    appId: '1:374957165391:ios:3d107866f218f5aa3fd33a',
    messagingSenderId: '374957165391',
    projectId: 'universityfirebase-155dd',
    storageBucket: 'universityfirebase-155dd.firebasestorage.app',
    iosBundleId: 'com.example.unihub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrTwLPthJrV0i4abC7Z4xxSzfXJ6-sZxk',
    appId: '1:374957165391:ios:3d107866f218f5aa3fd33a',
    messagingSenderId: '374957165391',
    projectId: 'universityfirebase-155dd',
    storageBucket: 'universityfirebase-155dd.firebasestorage.app',
    iosBundleId: 'com.example.unihub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpLg6f-iAMeuHE2R2HcavpOmx3uQUoZDo',
    appId: '1:374957165391:web:826b9879d182a3413fd33a',
    messagingSenderId: '374957165391',
    projectId: 'universityfirebase-155dd',
    authDomain: 'universityfirebase-155dd.firebaseapp.com',
    storageBucket: 'universityfirebase-155dd.firebasestorage.app',
  );
}
